config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path=>'',
                    :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                    :controllers => {:registrations => 'registrations' }
root 'pages#home'
resources :users, only: [:show]
resources :rooms


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  validates :home_type, presence: true

               validates :room_type, presence: true

               validates :accommodate, presence: true

               validates :bed_room, presence: true

               validates :bath_room, presence: true

               validates :listing_name, presence: true, length: {maximum: 75}

               validates :summary, presence: true, length: {maximum: 600}

               validates :address, presence: true

               validates :price, numericality: { only_integer: true, greater_than: 5 } 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :fullname, presence:true, length: {maximum: 50}
         has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
         :default_url => "/assets/default_image.png"
         validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
         has_many :rooms 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parametres, if: :devise_controller?
  protected
  def configure_permitted_parametres
    devise_parameter_sanitizer.permit(:sing_up, keys: [:fullname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def home
end 


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 protected

 def update_resource(resource, params)

     resource.update_without_password(params)

 end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :set_room, only:[:show, :edit, :update]
before_action :authenticate_user!, except: [:show] 
  def index

     @rooms = current_user.rooms

 end
 def new

 @room = current_user.rooms.build

end

def create

      @room = current_user.rooms.build(room_params)

      if @room.save

            redirect_to @room, notice:"Votre annonce a été ajouté avec succès"

      else

           render :new

      end

 end
     def show
     end
    def edit

   end
   def update
     if @room.update(room_params)

              redirect to @room, notice:"Modification enregistrée..."

       else

           render :edit

       end

  end
  private

      def set_room

             @room = Room.find(params[:id])

      end
      def room_params

      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room,
                                   :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet,
                                   :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price,
                                   :active)

 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

     def show

        @user = User.find(params[:id])

     end

end 

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
          user.avatar.url
      end
end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <%= link_to 'Donia', root_path, {:class=>"navbar-brand"} %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
<li>
  <%= link_to new_room_path do %>

 <i class="fa fa-home fa-lg"></i> Devenez hôte

 <% end %>

 </li>


            <% if(!user_signed_in?) %>
        <li><%=link_to 'Inscription',  new_user_registration_path %> </li>
        <li> <%=link_to 'Connexion',    new_user_session_path %></li>
        <% else %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %><%= current_user.fullname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Mes voyages',root_path %></li>
                <li><%= link_to 'Modifier mon profil',edit_user_registration_path %></li>

                <li role="separator" class="divider"></li>
      <li> <%=link_to 'Déconnexion',   destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% end %>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donia</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>


  </head>

  <body>
    <%= render 'layouts/navigation' %>
  <%= render 'shared/message' %>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/pages/home.html.erb
<h2> bienvenue </h2>
<%=link_to 'Inscription',  new_user_registration_path %>
<%=link_to 'Connexion',    new_user_session_path %>
<%=link_to 'Déconnexion',   destroy_user_session_path, method: :delete %>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Devenez hôte
    </div>
    <div class="panel-body">
        <div class="container">

            <%= form_for @room do |f| %>
            <%= render 'shared/errors' %>

            <div class="row">
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Genre d'habitation</label>
                            <%= f.select :home_type, [["Maison","Maison"], ["Appartement","Appartement"],
                            ["Bed & Breakfast", "Bed & Breakfast"]], id: "home_type",
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Type de logement</label>
                            <%= f.select :room_type, [["Logement entier","Logement entier"], ["Chambre privée","Chambre privée"],
                            ["Chambre partagée","Chambre partagée"]],
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label> Combien de voyageurs ?</label>
                            <%= f.select :accommodate, [["1 voyageur",1], ["2 voyageurs",2],
                            ["3 voyageurs", 3], ["4 voyageurs",4], ["5 voyageurs",5], ["6 voyageurs",6]],
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                </div>

            <div class="row">
                    <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Chambre(s)</label>
                        <%= f.select :bed_room, [["1 chambre",1], ["2 chambres",2],
                        ["3 chambres", 3], ["4 chambres ou plus",4]],
                        prompt: "Sélectionner le nombre", class: "form-control" %>
                    </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Salle(s) de bain</label>
                            <%= f.select :bath_room, [["1 salle de bain",1], ["2 salles de bain",2],
                            ["3 salles de bain", 3], ["4 salles de bain ou plus",4]],
                            prompt: "Sélectionner le nombre", class: "form-control" %>
                        </div>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Donnez un nom au logement</label>
                        <%= f.text_field :listing_name, placeholder: "Titre de l'annonce", class: "form-control" %>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Résumé</label>
                        <%= f.text_area :summary, rows:4, placeholder: "Décrivez le décor, l'ambiance, ce qui se trouve à proximité, etc...",
                        class: "form-control" %>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Adresse</label>
                        <%= f.text_field :address, placeholder: "Où est situé votre logement ?", class: "form-control" %>
                    </div>
                </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_wifi %> Wifi
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_tv %> Télévision
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_closet %> Penderie/Commode
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_shampoo %> Shampoing
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_kitchen %> Cuisine
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_breakfast %> Petit déjeuner, café, thé
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_heating %> Chauffage
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_air %> Climatisation
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Prix par nuit</label>
                        <div class="input-group">
                                <%= f.text_field :price, placeholder: "ex: 45€", class: "form-control" %>
                                <div class="input-group-addon">€</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <%= f.check_box :active %> Annonce active
                </div>
            </div>

            <div class="actions">
                      <%= f.submit "Je valide mon annonce", class: "btn btn-primary"%>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>

 <script type="text/javascript">

     <% resource.errors.full_messages.each do |msg| %>

               toastr.error('<%= msg %>')

     <% end %>

 </script>

 <% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>

 <script type="text/javascript">

     <% @room.errors.full_messages.each do |msg| %>

               toastr.error('<%= msg %>')

     <% end %>

 </script>

 <% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>

       <script type="text/javascript">

       <% flash.each do |f| %>

        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>

         toastr['<%= type %>']('<%= f[1] %>')

       <% end %>

       </script>

 <% end %>

app/views/users/show.html.erb
<div class="row">

       <div class="col-md-3">

                  <%= image_tag avatar_url(@user), class: "avatar-full" %>

                  <div class="panel panel-default">

                        <div class="panel-heading">Vérification</div>

                                <div class="panel-body">

                                       Email: <%= @user.email %><br>

                                       Tél: <%= @user.phone_number %>

                                </div>

                         </div>

                   </div>

          <div class="col-md-9">

                <h2><%= @user.fullname %></h2>

                <div class="description row-space-3">

                      <%= @user.description %>

                </div>

           </div>

 </div>